### ISSUE TITLE
Add a concept page for script runners (DOCKER and PROCESS runners) in the docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra.io#238]

**Comment by loicmathieu** [comment]
Maybe not a page inside [concepts](https://kestra.io/docs/concepts) because those page are for the main Kestra concepts and script is not  concept but a widely used tasks (some people will never used them).

But definitely their must be a page dedicated to script somewhere, my preference will be on the developer guide, in fact there is already a small section here: https://kestra.io/docs/developer-guide/storage#processing-data-using-scripts

Maybe we can enhance it, or add a page just undere.

**Comment by Ben8t** [comment]
done with https://kestra.io/docs/developer-guide/scripts#runners
