### ISSUE TITLE
Change on the homepage.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra.io#416]
### Feature description

When we discussed with @anna-geller the idea was to lighten the homepage and remove these two sections:

- ALL-INCLUSIVE DASHBOARD
- MAXIMIZE DATA WORKFLOW CAPABILITIES

Can you remove this ? (Keep it aside just in case.
Thanks

**Comment by anna-geller** [comment]
can you share the figma link? I think for the first one, we wanted to only change the wording a little + add dark theme UI screenshots

fully agree that the section "Uncover a Wide Range of Use Cases to Leverage Kestra's Potential" can be removed 👍 we now have the same info under solutions

**Comment by Nico-Kestra** [comment]
https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=144%3A355&mode=design&t=FIWSXOFxFJEQU4YB-1

**Comment by anna-geller** [comment]
this makes sense -- way cleaner this way, nice work!

**Comment by tchiotludo** [comment]
I don't remove ALL-INCLUSIVE DASHBOARD since I don't really like the ui : 
![image](https://github.com/kestra-io/kestra.io/assets/2064609/8e7b8456-612f-4931-a66d-435c2d5072c2)
we always alternate background from white to dark and if we remove the ui sections, we break this dynamic.
Reopen if I'm wrong

**Comment by Nico-Kestra** [comment]
I'll see what I can do. Thanks for all the closed issues.
