### ISSUE TITLE
Add documentation about editor keyboard shortcuts

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra.io#424]
### Feature description

Document all available shortcuts

**Comment by anna-geller** [comment]
I pushed directly to main:

"At the moment of writing this guide, [Kestra has 290+ tasks](../../plugins/index.md), which can be challenging to remember. That's why we provide an auto-completion feature to help you find the Task you need. Use the shortcut `CTRL or ⌘ + SPACE` to activate it. If you want to **comment out** some part of your code, you can use the `CTRL or ⌘ + K + C` shortcut, and to uncomment it, use `CTRL or ⌘ + K + U`. To remember it, `C` stands for `comment` and `U` stands for `uncomment`."
